# Generated by Django 4.2.5 on 2023-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='currency_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
